### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
freeze_multi_modal_projector: false # choices: [true, false]
freeze_language_model: false # choices: [true, false]
# train_mm_proj_only: false # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: loreal_train
template: qwen2_vl
cutoff_len: 16384
max_samples: 3000000
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 128

### output
output_dir: saves/loreal/trainfull/train0.8
# output_dir: saves/qwen2_vl-2b/full/sft/standred/0102_full_crohme_white
logging_steps: 1
save_steps: 9999 # 15个epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
resume_from_checkpoint: null

### eval
eval_dataset: loreal_test
#  ,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 100
