### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
train_mm_proj_only: false # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: crohme_train_nobox_white,0313_single_latte_error_detection_correction
template: qwen2_vl
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/sft-error/0313_full_crohme_baseline_find+fix_multi_error_1epoch
# output_dir: saves/qwen2_vl-2b/full/sft/standred/0102_full_crohme_white
logging_steps: 5
save_steps: 9999 # 15个epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: crohme_2014_nobox_white,crohme_2016_nobox_white,crohme_2019_nobox_white
#  ,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 90
