bf16: true
cutoff_len: 2048
dataloader_num_workers: 16
dataset: crohme_train
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_config.json
do_train: true
finetuning_type: full
freeze_language_model: false
freeze_multi_modal_projector: false
freeze_vision_tower: false
gradient_accumulation_steps: 16
image_max_pixels: 262144
learning_rate: 1.0e-05
logging_steps: 1
lr_scheduler_type: constant
max_samples: 200000
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
num_train_epochs: 2.0
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/wsd/0412_wsd_bs512_8k_2epoch-2
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 32
resume_from_checkpoint: null
save_only_model: true
save_steps: 9999
stage: sft
template: qwen2_vl
trust_remote_code: true
video_max_pixels: 16384
warmup_ratio: 0.1
