### model
model_name_or_path: Qwen/Qwen2-VL-2B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
train_mm_proj_only: false # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: crohme2023_train,crohme_train_nobox_white
template: qwen2_vl
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2_vl-2b/full/sft/standred/0118_full_crohme2023+crohme_qwen2b_newstandred
logging_steps: 10
save_steps: 328 # 15个epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: crohme2023_CROHME2014_test,crohme2023_CROHME2016_test,crohme2023_CROHME2019_test,crohme2023_CROHME2023_test,crohme_2014_nobox_white,crohme_2016_nobox_white,crohme_2019_nobox_white
#  ,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 328
