### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
train_mm_proj_only: false # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json
# deepspeed: examples/deepspeed/ds_z3_config.json


### dataset
dataset: im2latex100k_train
template: qwen2_vl
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/wsd/0226_full_im2latex100k_qwen2.5b_newstandred
logging_steps: 10
save_steps: 1176 # 15个epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 1.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: im2latex100k_validate
#  ,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 746
