### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
train_mm_proj_only: false # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: multi_task_ast_crohme_train
template: qwen2_vl
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/0214_multitask_btkatex_ast_crohme
# output_dir: saves/qwen2_vl-2b/full/sft/standred/0102_full_crohme_white
logging_steps: 4
save_steps: 280 # 15个epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: multi_task_tdv2_crohme_2014,multi_task_tdv2_crohme_2016,multi_task_tdv2_crohme_2019
#  ,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 70
