bf16: true
cutoff_len: 2048
dataloader_num_workers: 128
dataset: crohme_train,crohme_train_0410_final_tree,crohme2023_no_train_0410_final_tree,crohme2023_no_train_0410_final
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_config.json
do_train: true
finetuning_type: full
freeze_language_model: false
freeze_multi_modal_projector: false
freeze_vision_tower: false
gradient_accumulation_steps: 32
image_max_pixels: 262144
learning_rate: 1.0e-05
logging_steps: 1
lr_scheduler_type: cosine
max_samples: 3000000
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
num_train_epochs: 1.0
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/041x-all-methods/0418_full_crohme+2023_tree_1epoch_1-2
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 128
resume_from_checkpoint: null
save_only_model: true
save_steps: 50
stage: sft
template: qwen2_vl
trust_remote_code: true
video_max_pixels: 16384
warmup_ratio: 0.1
