### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256

### dataset
dataset: crohme_train # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2_vl-7b/lora/sft/rank256-epoch15-1117
logging_steps: 10
save_steps: 35
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: crohme_2014,crohme_2016,crohme_2019
val_size: 0
per_device_eval_batch_size: 32
eval_strategy: steps
eval_steps: 35
